{"name": "TC01: Login to Grafana", "status": "broken", "statusDetails": {"message": "TypeError: WebDriver.__init__() got an unexpected keyword argument 'service'", "trace": "request = <SubRequest 'init_web_driver' for <Function test_verify_login>>\n\n    @pytest.fixture(scope=\"class\")\n    def init_web_driver(request):\n        if get_data(\"ExecuteApplitools\").lower() == 'yes':\n            globals()['driver'] = get_web_driver()\n        else:\n>           edriver = get_web_driver()\n\nconftest.py:42: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nconftest.py:96: in get_web_driver\n    driver = get_chrome()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\n    def get_chrome():\n>       chrome_driver = webdriver.Chrome(service=ChromeService(ChromeDriverManager().install()))  # Selenium 4.x\nE       TypeError: WebDriver.__init__() got an unexpected keyword argument 'service'\n\nconftest.py:125: TypeError"}, "description": "Verify a successful login to Grafana", "start": 1682172167973, "stop": 1682172167973, "uuid": "761037f1-91a2-4b77-9d3b-c3a1f43aa101", "historyId": "54e61a4397564b26acdf4b5fe208f939", "testCaseId": "4727d0277c9099c0888dae150522b402", "fullName": "test_cases.test_web.TestWeb#test_verify_login", "labels": [{"name": "tag", "value": "run_this"}, {"name": "tag", "value": "sanity"}, {"name": "tag", "value": "@pytest.mark.usefixtures('init_web_driver')"}, {"name": "parentSuite", "value": "test_cases"}, {"name": "suite", "value": "test_web"}, {"name": "subSuite", "value": "TestWeb"}, {"name": "host", "value": "BarLaptop"}, {"name": "thread", "value": "20408-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_cases.test_web"}]}