{"name": "TC03: Create and verify new users", "status": "broken", "statusDetails": {"message": "TypeError: WebDriver.__init__() got an unexpected keyword argument 'service'", "trace": "request = <SubRequest 'init_web_driver' for <Function test_verify_login>>\n\n    @pytest.fixture(scope=\"class\")\n    def init_web_driver(request):\n        if get_data(\"ExecuteApplitools\").lower() == 'yes':\n            globals()['driver'] = get_web_driver()\n        else:\n>           edriver = get_web_driver()\n\nconftest.py:42: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nconftest.py:96: in get_web_driver\n    driver = get_chrome()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\n    def get_chrome():\n>       chrome_driver = webdriver.Chrome(service=ChromeService(ChromeDriverManager().install()))  # Selenium 4.x\nE       TypeError: WebDriver.__init__() got an unexpected keyword argument 'service'\n\nconftest.py:125: TypeError"}, "description": "This test create new users and check that the new users are displayed", "start": 1682172172219, "stop": 1682172172219, "uuid": "f531193e-c1e5-44e6-a780-f52f37b61e26", "historyId": "25d6e6cc6674f375e6317b3d13101cfc", "testCaseId": "c4400c496e6ec93c66d5ba4a090a9e80", "fullName": "test_cases.test_web.TestWeb#test_verify_new_users", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('init_web_driver')"}, {"name": "parentSuite", "value": "test_cases"}, {"name": "suite", "value": "test_web"}, {"name": "subSuite", "value": "TestWeb"}, {"name": "host", "value": "BarLaptop"}, {"name": "thread", "value": "20408-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_cases.test_web"}]}